[build]
  command = "pip install -r requirements.txt && pip install gunicorn"
  publish = "."
  functions = ".netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[dev]
  command = "gunicorn flask_app:app"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
[[plugins]]
  package = "netlify-plugin-persist-sqlite"
  
  [plugins.inputs]
    include = ["sanskrit.db"]
