[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"
  # The actual MongoDB URI will be set in Netlify environment settings
  # This is just a placeholder
  MONGODB_URI = "mongodb+srv://placeholder:placeholder@cluster.mongodb.net/"
  MONGODB_DB = "tattva"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200