[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = ".netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
[[plugins]]
  package = "netlify-plugin-persist-sqlite"
  
  [plugins.inputs]
    include = ["sanskrit.db"]
